task "default" do |t|
	system "bundle exec slimrb -l index.slim index.html"
	system "bundle exec compass compile"
end

task "watch" do |t|
	system "compass watch"
end

task "deploy" do |t|
	system "git add ."
	system "git commit -am Update"
	system "git push --all"
end